/* globals hopscotch: false */

// Define the tour!
var tour = {
  id: "testspace-demo",
  steps: [
    
    {
      title: "Unified Quality Metrics",
      content: "Monitor the health of projects, repositories, local branches, pull requests, etc., all from a single view.",
      target: "project-142",
      placement: "top",
      arrowOffset: 'center',
    },
    {
      title: "Include Important Metrics",
      content: "Use code coverage, static analysis, and even custom metrics as part of the build status.",
      target: "project-142",
      placement: "top",
      xOffset: 585,
      arrowOffset: 'center',
      multipage: true,
      onNext: function() {
        window.location = "https://demo.stridespace.com/projects/s2technologies:testspace/spaces/master/metrics";
      },
    },
    {
      title: "Historical Tracking of Metrics",
      target: document.querySelector(".metrics-header"),
      content: "Source code changes, tests growth, regressions, and more. Chart your <a href=\"https://blog.testspace.com/turn-log-files-into-actionable-metrics/\" target=\"_blank\">own metric data</a> from log files.",
      placement: "top",
      arrowOffset: 'center',
      yOffset: 34,
      xOffset: 300,
      multipage: true,
      onNext: function() {
        window.location = "https://demo.stridespace.com/projects/s2technologies:testspace/spaces/master";
      },
      onPrev: function() {
        window.location = "https://demo.stridespace.com";
      }
    },
    
    {
      title: "Manage Test Content",
      content: "Organized your results to reflect the Test Plan. Leverage fast navigation and failure triage filtering. Check out our blog article on <a href=\"https://blog.testspace.com/filtering-and-tracking-test-failures/\" target=\"_blank\">Filtering and Tracking</a> for more details.",
      target: "schema-orphans",
      placement: "top",
      arrowOffset: 'center',
      multipage: true,
      onNext: function() {
        window.location = "https://demo.stridespace.com/projects/s2technologies:testspace/insights";
      },
      onPrev: function() {
        window.location = "https://demo.stridespace.com/projects/s2technologies:testspace/spaces/master/metrics";
      }
    },
    {
      title: "Insights: Optimize Process",
      content: "Continuously assess your test process using computational analysis. Check out our blog article on <a href=\"https://blog.testspace.com/testspace-insights/\" target=\"_blank\">Testspace Insights</a> for more details.",
      target: document.querySelector(".insights-header"),
      placement: "bottom",
      arrowOffset: 'center',
      xOffset: 340,
      yOffset: 214,
      onPrev: function() {
        window.location = "https://demo.stridespace.com/projects/s2technologies:testspace/spaces/master";
      }
    },
    {
      title: "Results Strength",
      content: "Indicator and metrics presenting the consistency of results being generated by your test automation.",
      target: document.querySelector(".insights-header"),
      placement: "top",
      arrowOffset: 'center',
      yOffset: 34,
    },
    {
      title: "Test Effectiveness",
      content: "Indicator and metrics assessing the effectiveness of automated tests capturing side-effects based on change.",
      target: document.querySelector(".insights-header"),
      placement: "top",
      arrowOffset: 'center',
      xOffset: 300,
      yOffset: 34
    },
    {
      title: "Workflow Efficiency",
      content: "Indicator and metrics analyzing the efficiency of resolving test case failures and closing pull requests.",
      target: document.querySelector(".insights-header"),
      placement: "top",
      arrowOffset: 'center',
      xOffset: 700,
      yOffset: 34
    }
    
  ],
  
  onClose: function () {
    console.log("onClose ..");
  },
  
  onEnd: function () {
    console.log("onEnd ..");
    window.location = "https://demo.stridespace.com";
  },
  
  onError: function () {
    console.log("onError .."); 
    hopscotch.endTour();
  },
  
  skipIfNoElement: false,
  showPrevButton: true,
  scrollTopMargin: 100
};

var state = hopscotch.getState();
console.log(state);
hopscotch.startTour(tour);


